#!/usr/bin/env bash
# a Bash script that will display information about subdomains
# USAGE: ./1-world_wide_web <DOMAIN> [<SUBDOMAIN>]
# shellcheck disable=SC2086

subdomains=$(awk '{print $2 ? $2 : "www lb-01 web-01 web-02"}' <<< "$@")

for sub in $subdomains; do
	read -r _ _ _ recd dest <<< "$(dig +noall +answer $sub.$1)"
	echo "The subdomain $sub is a $recd record and points to $dest"
done
