#!/usr/bin/env bash
# Install and configure HAproxy on your `lb-01` server.
apt-get install software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-1.8 -y
apt-get update
apt-get install haproxy=1.8.\*
# TODO config round robin
service haproxy restart
