#!/usr/bin/env bash
# Displays a list of currently running processes
# Shows all processes, for all users, including those which might not have a TTY
# Displayed in a user-oriented format
# Shows the process hierarchy
ps axuf
