#!/usr/bin/env bash
# This script that loops from 1 to 10 and
# displays "bad luck" for the 4th loop iteration
# displays "good luck" for the 8th loop iteration
# displays "Holberton School" for the other iterations
i=0
while [ $i -lt 10 ]; do
	let i++
	if [ $i -eq 4 ]; then
		echo "bad luck"
	elif [ $i -eq 8 ]; then
		echo "good luck"
	else
		echo "Holberton School"
	fi
done
