#!/usr/bin/env bash
# Install the `ufw` firewall and configure so it blocks all incoming
# traffic, except the TCP ports 22 (SSH), 443 (HTTPS) and 80 (HTTP).
apt install ufw -y
ufw enable
ufw allow 22/tcp
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
