#!/usr/bin/env bash
# Transfers a file from our client to a server
if [ $# -eq 4 ]; then
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"'@'"$2":~/
	# Translates:
	# 	0-transfer_file example.file 35.237.166.85 ubuntu ~/.ssh/holberton
	# Into:
	# 	scp -i ~/.ssh/holberton -o StrictHostKeyChecking=no example.file ubuntu@35.237.166.85:~/
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
