#!/usr/bin/env bash
# Fixes server so that Nginx is running as the `nginx` user

# Nginx must be listening on all active IPs on port 8080
sed -i 's/80 default/8080 default/' /etc/nginx/sites-available/default

# Nginx must be running as `nginx` user
sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
chmod +r /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
